version: '3'
services:

  aria2-server:
    image: devifish/aria2
    container_name: aria2-server
    restart: always
    network_mode: "host"
    volumes:
      - ${DATA_DIR}:/data
      - ${DOWNLOAD_DIR}:/downloads
